### ISSUE TITLE
Controller e rota para retornar os casos de teste de uma suite

### ISSUE THREAD

**Issue by rodrigocan** [ictestufba/ictest-backend#23]

**Comment by barbluz** [comment]
@rodrigocan Os casos de teste aparecem na lista de detalhe da suite, precisa mesmo de uma outra rota só pra retornar os casos de teste?

**Comment by rodrigocan** [comment]
Verdade Bárbara, isso depende muito da nossa escolha. Se quisermos 2 opções de retorno ou 1 opção só com todos os detalhes. Nesse caso podemos simplificar e ficar só com essa rota de detalhes da suíte mesmo. Basicamente é escolher entre retornar um json maior ou menor... Vou dar como resolvida essa issue.
